// Code generated by protoc-gen-micro
// source: register.proto
package service

import (
	"context"

	micro_api "github.com/unistack-org/micro/v3/api"
	micro_client "github.com/unistack-org/micro/v3/client"
	micro_server "github.com/unistack-org/micro/v3/server"
)

// NewRegisterEndpoints provides api endpoints metdata for Register service
func NewRegisterEndpoints() []*micro_api.Endpoint {
	var endpoints []*micro_api.Endpoint
	return endpoints
}

// RegisterService interface
type RegisterService interface {
	LookupService(context.Context, *LookupRequest, ...micro_client.CallOption) (*LookupResponse, error)
	Register(context.Context, *Service, ...micro_client.CallOption) (*EmptyResponse, error)
	Deregister(context.Context, *Service, ...micro_client.CallOption) (*EmptyResponse, error)
	ListServices(context.Context, *ListRequest, ...micro_client.CallOption) (*ListResponse, error)
	Watch(context.Context, *WatchRequest, ...micro_client.CallOption) (Register_WatchService, error)
}

type Register_WatchService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*Result, error)
}

// Micro server stuff

// RegisterHandler server handler
type RegisterHandler interface {
	LookupService(context.Context, *LookupRequest, *LookupResponse) error
	Register(context.Context, *Service, *EmptyResponse) error
	Deregister(context.Context, *Service, *EmptyResponse) error
	ListServices(context.Context, *ListRequest, *ListResponse) error
	Watch(context.Context, *WatchRequest, Register_WatchStream) error
}

// RegisterRegisterHandler registers server handler
func RegisterRegisterHandler(s micro_server.Server, sh RegisterHandler, opts ...micro_server.HandlerOption) error {
	type register interface {
		LookupService(context.Context, *LookupRequest, *LookupResponse) error
		Register(context.Context, *Service, *EmptyResponse) error
		Deregister(context.Context, *Service, *EmptyResponse) error
		ListServices(context.Context, *ListRequest, *ListResponse) error
		Watch(context.Context, micro_server.Stream) error
	}
	type Register struct {
		register
	}
	h := &registerHandler{sh}
	for _, endpoint := range NewRegisterEndpoints() {
		opts = append(opts, micro_api.WithEndpoint(endpoint))
	}
	return s.Handle(s.NewHandler(&Register{h}, opts...))
}

type Register_WatchStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Result) error
}
